CREATE TABLE IF NOT EXISTS ITEM (
    ITEM_PK INTEGER PRIMARY KEY AUTOINCREMENT,
    ITEM_ORIGIN_URL TEXT NOT NULL,
    ITEM_TYPE TEXT CHECK(ITEM_TYPE IN ('temp', 'perm', 'count')),
    ITEM_SHORT_PATH TEXT NOT NULL,
    ITEM_INIT_COUNT INTEGER,
    ITEM_CURRENT_COUNT INTEGER,
    ITEM_EXP_SEC INTEGER,
    ITEM_CREATE_TIME DATETIME NOT NULL,
    UNIQUE (ITEM_ORIGIN_URL),
    UNIQUE (ITEM_SHORT_PATH)
);

CREATE TABLE IF NOT EXISTS USER (
    USER_PK INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID TEXT NOT NULL,
    USER_PW TEXT NOT NULL,
    UNIQUE (USER_ID)
);